top_skills:
  - Internet of Things (IoT)
  - Amazon Web Services (AWS)
  - Embedded Software Programming
  - Artificial Intelligence (AI)
  - Full Stack Development (MERN)
  - MQTT (protocol)
  - Automation Scripts (Macros, VBA)
  - Database Management (SQL)
  - GitHub
remote_theme: daattali/beautiful-jekyll
title: "Sukhmeet Singh Hora"
description: "Welcome to my portfolio website!"
author: "Sukhmeet Singh Hora"
theme_skin: "dark"  # or choose "light"
social-network-links:
  linkedin: sukhmeet-hora
  github: sukhmeet468
